/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProductRegistry } from "./ProductRegistry";
export * as factories from "./factories";
export { ProductRegistry__factory } from "./factories/ProductRegistry__factory";
